# Generated by Django 4.1 on 2022-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='todays',
            field=models.BooleanField(default=False),
        ),
    ]
