# Generated by Django 4.1.7 on 2023-03-16 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_uservideorelation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservideorelation",
            name="collected",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
