# Generated by Django 4.1 on 2023-02-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_todays"),
        ("users", "0002_alter_user_managers_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="videos",
            field=models.ManyToManyField(related_name="users", to="videos.video"),
        ),
    ]
